#flatten_single_child_sections: true
nav:
  - Home: index.md
  - models-overview.md
  - Models:
      - Oral:
        - glob: "models/oral/*"
          flatten_single_child_sections: true
      - Inhalation:
        - glob: "models/inhalation/*"
          flatten_single_child_sections: true
  - Simulations:
      - "simulation/*"
  - Downloads: downloads.md
  - About: about.md
