flatten_single_child_sections: true
nav:
  - Home: index.md
  - Models:
      - models-overview.md
      - "models/oral"
      - "models/inhalation"
  - Simulations:
      - "simulation/oral"
      - "simulation/inhalation"
  - About: about.md
